version: "3"
services:
  postgres:
    container_name: postgres-hacktiv
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_gin_jwt
    ports:
    - "5432:5432"